# Generated by Django 5.1.15 on 2026-06-14 08:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='bio')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff_photos/', verbose_name='photo')),
                ('working_days', models.CharField(default='0,1,2,3,4', help_text='Comma-separated day numbers: 0=Monday … 6=Sunday', max_length=20, verbose_name='working days')),
                ('start_time', models.TimeField(default=datetime.time(9, 0), verbose_name='start time')),
                ('end_time', models.TimeField(default=datetime.time(18, 0), verbose_name='end time')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='businesses.business')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'staff member',
                'verbose_name_plural': 'staff',
            },
        ),
    ]
